---
- name: "Checking for latest go version"
  stat:
    path: "{{ ansible_env.HOME }}/go/bin//go1.21.0"
  register: go_file

- name: "Upgrade Golang package"
  shell: |
    go install golang.org/dl/go1.21.0@latest
    {{ ansible_env.HOME }}/go/bin//go1.21.0 download
  when: go_file.stat.islnk is not defined

- name: "Deleting current go link"
  file:
    path: "/usr/bin/go"
    state: absent
  become: true
  become_method: sudo
  when: go_file.stat.islnk is not defined

- name: "Re-linking go to new binary"
  file:
    src: "{{ ansible_env.HOME }}/go/bin//go1.21.0"
    dest: "/usr/bin/go"
    state: hard
  become: true
  become_method: sudo
  when: go_file.stat.islnk is not defined