---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo"
      debug:
        msg: "success"
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    