---
- name: "Copy BashRC"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"
- name: "Copy Bash Aliases"
  copy:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}"
- name: "Restoring MATE profile to default from dump"
  shell:
    cmd: "dconf load /org/mate/terminal/profiles/default/ < {{ role_path }}/files/profile.dump"